/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.OrdenTrabajo;
import model.Platillo;

/**
 *
 * @author polares
 */
public class VentanaPlatillosCliente extends VentanaBase {

    /**
     * Creates new form VentanaPlatillosCliente
     */
    public VentanaPlatillosCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        listaPlatillos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOrdenes = new javax.swing.JTable();
        anadirBoton = new javax.swing.JButton();
        botonOrdenar = new javax.swing.JButton();
        barraCocina = new javax.swing.JProgressBar();
        barraEspera = new javax.swing.JProgressBar();
        barraListos = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        labelCocinando = new javax.swing.JLabel();
        labelEsperando = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelEmpacando = new javax.swing.JLabel();
        labelListos = new javax.swing.JLabel();
        cerrarSesionBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingreso de Pedidos");

        listaPlatillos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Platillos");

        tablaOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Orden", "Platillo", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(tablaOrdenes);

        anadirBoton.setText("Añadir a Orden de Trabajo");
        anadirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirBotonActionPerformed(evt);
            }
        });

        botonOrdenar.setText("Ordenar Pedido");
        botonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrdenarActionPerformed(evt);
            }
        });

        jLabel3.setText("Cocina");

        labelCocinando.setText("Cocinando...");

        labelEsperando.setText("Esperando...");

        jLabel6.setText("Cola de Espera");

        jLabel7.setText("Platillos Listos");

        labelEmpacando.setText("Empacando...");

        labelListos.setText("Ordenes Listas: ");

        cerrarSesionBoton.setText("Cerrar Sesion");
        cerrarSesionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(219, 219, 219)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cerrarSesionBoton))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(listaPlatillos, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(88, 88, 88)
                            .addComponent(anadirBoton))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(barraCocina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barraListos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelListos, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelEsperando))
                                .addComponent(barraEspera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelCocinando))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelEmpacando))))
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonOrdenar)
                        .addGap(248, 248, 248))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cerrarSesionBoton))
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaPlatillos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anadirBoton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonOrdenar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelEsperando))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelCocinando))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelEmpacando))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraListos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelListos)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anadirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirBotonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.tablaOrdenes.getModel();
        modelo.setRowCount(0);
       
        String plat = (String) this.listaPlatillos.getSelectedItem(); //Se obtiene el item seleccionado
        String platillo = plat.split(" - ")[0];
        this.getControlador().getControladorUsuarios().crearOrdenTrabajo(platillo); 
        
        ArrayList<OrdenTrabajo> ordenes = this.getControlador().getClienteActual().obtenerOrdenesSinAsignar();

        ArrayList<String[]> ordenesRow = new ArrayList<String[]>();
        for(OrdenTrabajo orden: ordenes) {
            ordenesRow.add(new String[]{ orden.getId(), orden.getPlatillo(), "1" } );
        }
        
        //Se llena la tabla
        for (String[] orden : ordenesRow) {
            modelo.addRow(orden);
        }
    }//GEN-LAST:event_anadirBotonActionPerformed

    private void botonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrdenarActionPerformed
        // TODO add your handling code here:
        this.getControlador().iniciarFlujoPedido();
    }//GEN-LAST:event_botonOrdenarActionPerformed

    private void cerrarSesionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBotonActionPerformed
        this.getControlador().getClienteActual().getVentanaPlatillosCliente().setVisible(false);
        this.cerrarSesion();
    }//GEN-LAST:event_cerrarSesionBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPlatillosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPlatillosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPlatillosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPlatillosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPlatillosCliente().setVisible(true);
            }
        });
    }

    public JProgressBar getBarraCocina() {
        return barraCocina;
    }

    public void setBarraCocina(JProgressBar barraCocina) {
        this.barraCocina = barraCocina;
    }

    public JProgressBar getBarraEspera() {
        return barraEspera;
    }

    public void setBarraEspera(JProgressBar barraEspera) {
        this.barraEspera = barraEspera;
    }

    public JProgressBar getBarraListos() {
        return barraListos;
    }

    public void setBarraListos(JProgressBar barraListos) {
        this.barraListos = barraListos;
    }

    public JLabel getLabelCocinando() {
        return labelCocinando;
    }

    public void setLabelCocinando(JLabel labelCocinando) {
        this.labelCocinando = labelCocinando;
    }

    public JLabel getLabelEmpacando() {
        return labelEmpacando;
    }

    public void setLabelEmpacando(JLabel labelEmpacando) {
        this.labelEmpacando = labelEmpacando;
    }

    public JLabel getLabelEsperando() {
        return labelEsperando;
    }

    public void setLabelEsperando(JLabel labelEsperando) {
        this.labelEsperando = labelEsperando;
    }

    public JLabel getLabelListos() {
        return labelListos;
    }

    public void setLabelListos(JLabel labelListos) {
        this.labelListos = labelListos;
    }
    
    public void llenarListaPlatillos() {
        ArrayList<Platillo> platillos = this.getControlador().getModelo().getListaPlatillos();
        this.listaPlatillos.removeAllItems(); //Limpio la lista desplegable
        for(Platillo platillo : platillos) {
            this.listaPlatillos.addItem(platillo.getId()+" - " + platillo.getNombre() + " - " + platillo.getPrecioManoObra());
        }
    }
    
    public void vaciarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) this.tablaOrdenes.getModel();
        modelo.setRowCount(0);
    }

    public void llenarPlatillosListos(Cliente c) {
        this.labelListos.setText("Listos: ");
        for(OrdenTrabajo o: c.getListaOrdenes()) {
            if(o.getEstado() == 3) {
                this.labelListos.setText(this.labelListos.getText() + " " + o.getId());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirBoton;
    private javax.swing.JProgressBar barraCocina;
    private javax.swing.JProgressBar barraEspera;
    private javax.swing.JProgressBar barraListos;
    private javax.swing.JButton botonOrdenar;
    private javax.swing.JButton cerrarSesionBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCocinando;
    private javax.swing.JLabel labelEmpacando;
    private javax.swing.JLabel labelEsperando;
    private javax.swing.JLabel labelListos;
    private javax.swing.JComboBox<String> listaPlatillos;
    private javax.swing.JTable tablaOrdenes;
    // End of variables declaration//GEN-END:variables
}
